url: https://marinahuber.github.io
title: iOS Engineering
subtitle: Discover mobile recipes.
google_analytics_tracking_id: UA-12450662-3
permalink: /blog/:year/:month/:day/:title/
baseurl: "/blog" # the subpath of your site, e.g. /blog/
github_username: MarinaHuber

subscribe_rss: /feed.xml

disqus_short_name: artsy
disqus_show_comment_count: false

exclude: ["vendor", "LICENSE", "_posts/LICENSE"]

plugins: ["jekyll-redirect-from", "jekyll-paginate"]

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false

paginate: 6
paginate_path: "/blog/"

recent_posts: 5
excerpt_link: "Read More"
titlecase: true
category_dir: blog/categories

