source "https://rubygems.org"

gem 'rake'
gem 'jekyll'
gem 'octopress-hooks'
gem 'kramdown-parser-gfm'
gem 'pry'
gem 'mp3info'
gem 'aws-sdk-s3'
gem 'jekyll-redirect-from'
gem 'jekyll-paginate'
gem 'byebug'
gem 'weaviate-ruby'
gem "github-pages", group: :jekyll_plugins
gem "jekyll-theme-primer"

group :distribution do
  gem 'danger'
end
